name: Release SudoDEM3D

on:
  release:
    types: [prereleased]

env:
  BUILD_TYPE: Release

jobs:
  SudoDEM3Drelease:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4

    - name: install basic 3rdlibs
      shell: bash
      run: |
        mkdir -p 3rdlib/3rdlibs/py
        cd scripts
        sh install3rd_base.sh

    - name: compile 3rdlibs
      if: false #do not compile
      shell: bash
      run: |
        cd scripts
        sh install3rdcore_sudosimlab.sh

    - name: download precompiled 3rdlibs
      shell: bash
      run: |
        wget https://github.com/SudoDEM/3rdlibs/releases/latest/download/tools-${{matrix.os}}.tar.xz
        tar xf tools-${{matrix.os}}.tar.xz
        wget https://github.com/SudoDEM/3rdlibs/releases/latest/download/3rdlibs-${{matrix.os}}.tar.xz
        tar xf 3rdlibs-${{matrix.os}}.tar.xz
        cp -rf 3rdlib/HeaderLib/lib/* 3rdlibs/
        cp -r 3rdlib/HeaderLib/lib/py/* 3rdlibs/py/

    - name: compile SudoDEM3D
      shell: bash
      run: |
        cd scripts
        sh firstCompile_SudoDEM3D.sh

    - name: Archive compiled SudoDEM3D
      working-directory: ${{github.workspace}}/
      run: |
          tar cfJ SudoDEM3D-${{matrix.os}}.tar.xz sudodeminstall

    - name: upload compiled SudoDEM3D
      uses: actions/upload-artifact@v3
      with:
        name: SudoDEM3D-${{matrix.os}}
        path: |
          ${{github.workspace}}/SudoDEM3D-${{matrix.os}}.tar.xz

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/SudoDEM3D-${{matrix.os}}.tar.xz
        tag: ${{ github.ref }}
        overwrite: true