name: Release SudoDEM2D

on:
  release:
    types: [prereleased]

env:
  BUILD_TYPE: Release

jobs:
  releaseSudoDEM2D:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: install basic 3rdlibs
      shell: bash
      run: |
        cd scripts
        sh install3rd_base.sh

    - name: compile 3rdlibs
    if: false #do not compile
    shell: bash
    run: |
      cd scripts
      sh install3rdcore_sudosimlab.sh

    - name: download precompiled 3rdlibs
      shell: bash
      run: |
        mkdir -p 3rdlib/3rdlibs/py
        wget https://github.com/SudoDEM/3rdlibs/releases/latest/download/3rdlibs-${{matrix.os}}.tar.xz
        tar xf 3rdlibs-${{matrix.os}}.tar.xz ./3rdlib/
        cd 3rdlib
        cp -rf HeaderLib/lib/* 3rdlibs/
        cp -r HeaderLib/lib/py/* 3rdlibs/py/

    - name: compile SudoDEM2D
      shell: bash
      run: |
        cd scripts
        sh firstCompile_SudoDEM2D.sh

    - name: Archive compiled SudoDEM2D
      working-directory: ${{github.workspace}}/
      run: |
          tar cfJ SudoDEM2D-${{matrix.os}}.tar.xz sudodeminstall

    - name: upload compiled SudoDEM2D
      uses: actions/upload-artifact@v3
      with:
        name: SudoDEM2D-${{matrix.os}}
        path: |
          ${{github.workspace}}/SudoDEM2D-${{matrix.os}}.tar.xz